"""add photo column in post

Revision ID: 2f7dc03243b3
Revises: 981d7dad41fc
Create Date: 2022-05-22 13:46:38.298304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7dc03243b3'
down_revision = '981d7dad41fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.String(), server_default='photos/default.jpg', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_path')
    # ### end Alembic commands ###
