"""post default image remove

Revision ID: 32e4c8d36c5f
Revises: 2f7dc03243b3
Create Date: 2022-05-22 14:00:41.793948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e4c8d36c5f'
down_revision = '2f7dc03243b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
