"""post default image remove

Revision ID: 76f6afe5510d
Revises: 32e4c8d36c5f
Create Date: 2022-05-22 14:02:21.956650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f6afe5510d'
down_revision = '32e4c8d36c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
